import { Button, Center, HStack, Heading, Stack } from '@chakra-ui/react';
import Head from 'next/head';
import { useRouter } from 'next/router';

export default function Home() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Kin Kerfuffle</title>
        <meta name="description" content="Generated by create chext app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Center w="full" h="100vh">
        <Stack>
          <Heading textAlign="center">Kin Kerfuffle</Heading>
          <HStack spacing={4}>
            <Button
              onClick={() => {
                router.push('/game');
              }}
            >
              Start Game
            </Button>
          </HStack>
        </Stack>
      </Center>
    </>
  );
}
